blank_issues_enabled: false
contact_links:
  - name: â“ Questions and Help
    url: https://github.com/php-webdriver/php-webdriver/discussions
    about: Please ask and answer questions here
  - name: ğŸ’¡ Ideas and feature requests
    url: https://github.com/php-webdriver/php-webdriver/discussions
    about: Suggest an idea for php-webdriver
